name: Deploy React App

on:
  push:
    branches:
      - main  # Runs when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Navigating to project directory..."
            cd /var/www/html/GSP_Frontend

            echo "Pulling latest changes from GitHub..."
            sudo git pull origin main

            echo "Installing dependencies & building React app..."
            sudo npm install
            sudo npm run build

            echo "Restarting Nginx with sudo privileges..."
            sudo systemctl restart nginx

            echo "Deployment completed successfully!"
